version: "3"

services:
  composer:
    container_name: "${DOCKER_PROJECT_NAME}_composer"
    environment:
      COLUMNS: 80
      PHP_FPM_GROUP: wodby
      PHP_FPM_USER: wodby
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: develop,debug,coverage
      PHP_XDEBUG_DISCOVER_CLIENT_HOST: 1
      PHP_XDEBUG_CLIENT_HOST: host.docker.internal
      PHP_XDEBUG_START_WITH_REQUEST: 'trigger'
      PHP_XDEBUG_TRIGGER_VALUE: 'enable'
    env_file:
      - .env
    image: wodby/php:7.4-dev-macos-4.33.4
    volumes:
      - "./:/var/www/html"
