#file: noinspection SpellCheckingInspection
name: CodeChecks

on:
    pull_request: null
    push:
        branches:
            - develop
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        name: Tests
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    coverage: none
                    tools: composer:v2
            -   run: composer clearcache
            -   run: composer install --no-progress --ansi
            -   run: composer test

    static_analysis:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        name: Static Analysis
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    coverage: none
                    tools: composer:v2
            -   run: composer clearcache
            -   run: composer install --no-progress --ansi
            -   run: composer phpstan-cli
