#file: noinspection SpellCheckingInspection
name: CodeChecks

on:
    pull_request: null
    push:
        branches:
            - develop
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        name: Tests
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.3'
                    coverage: none
                    tools: composer:v2
            -   run: composer clearcache
            -   run: composer install --no-progress --ansi
            -   run: composer test

    static_analysis:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        name: Static Analysis
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.3'
                    coverage: none
                    tools: composer:v2
            -   run: composer clearcache
            -   run: composer install --no-progress --ansi
            -   run: composer phpstan-cli

            -   uses: timkrase/phpunit-coverage-badge@v1.2.0
                with:
                    coverage_badge_path: 'badge-coverage.svg'
                    push_badge: true
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
